extension_dir="ext"
date.timezone="UTC"

curl.cainfo="C:/Users/Administrator/Documents/Websites/Matutu System/IT-Project-148585-151631/.tools/php-8.2.30/cacert.pem"
openssl.cafile="C:/Users/Administrator/Documents/Websites/Matutu System/IT-Project-148585-151631/.tools/php-8.2.30/cacert.pem"

extension=curl
extension=fileinfo
extension=intl
extension=mbstring
extension=openssl
extension=pdo_pgsql
extension=pdo_mysql
extension=pdo_sqlite
extension=pgsql
extension=sodium
extension=sqlite3
extension=zip
